{
 "title": "Swisstronik",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "addressGV",
    "label": "addressGV",
    "query": {
     "query": "label_values({address=\"swtrvaloper1fwk6ludk27ppe4sa634p39ahlx6prp6c8zaz5c\"},address)"
    }
   },
   {
    "name": "addressNW",
    "label": "addressNW",
    "query": {
     "query": "label_values({address=\"swtrvaloper1x9djmrsvrf60xze5vj4pv52khjhskyqpfwjf86\"},address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "NodeWarrior", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (cosmos_validators_exporter_missed_blocks{address=\"$addressNW\"} / on (chain) cosmos_validators_exporter_missed_blocks_window) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Name",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "options": {
    "content": "## [NodeWarrior](https://nodewarrior.xyz) "
   }
  },
  {
   "title": "Jail",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_jailed{address=\"$addressGV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_active{address=\"$addressGV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens Staked",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_total_delegations{address=\"$addressGV\"}/1000000000000000000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_rank{address=\"$addressNW\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_validators_count{address=\"$addressGV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Commision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_commission{address=\"$addressNW\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_missed_blocks{address=\"$addressNW\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (cosmos_validators_exporter_missed_blocks{address=\"$addressNW\"} / on (chain) cosmos_validators_exporter_missed_blocks_window) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}